import React, { useEffect, useState, useCallback } from 'react';
import {
  View, Text, StyleSheet, ScrollView, TouchableOpacity,
  RefreshControl, StatusBar, Share, Alert, Image,
} from 'react-native';

import { SafeAreaView } from 'react-native-safe-area-context';
import { Ionicons } from '@expo/vector-icons';
import { colors } from '../../theme/colors';
import { typography } from '../../theme/typography';
import StatsCard from '../../components/StatsCard';
import LoadingSpinner from '../../components/LoadingSpinner';
import { dashboardAPI } from '../../services/api';
import { useAuth } from '../../context/AuthContext';

export default function CSODashboardScreen({ navigation }) {
  const { user, logout } = useAuth();
  const [stats, setStats] = useState(null);
  const [loading, setLoading] = useState(true);
  const [refreshing, setRefreshing] = useState(false);

  const fetchStats = useCallback(async () => {
    try {
      const res = await dashboardAPI.getCSOStats();
      setStats(res.data.data ?? res.data);
    } catch (err) {
      console.warn('Dashboard fetch failed:', err.message);
    } finally {
      setLoading(false);
      setRefreshing(false);
    }
  }, []);

  useEffect(() => { fetchStats(); }, [fetchStats]);

  const onRefresh = () => { setRefreshing(true); fetchStats(); };

  const handleShare = async () => {
    try {
      const summary = `
KIAL Security Compliance Report
------------------------------
Date: ${new Date().toLocaleDateString()}
Total Entities: ${stats?.totalEntities || 0}
Total Staff: ${stats?.totalStaff || 0}
Compliance Rate: ${stats?.complianceRate || 0}%
Pending Approvals: ${stats?.pendingApprovals || 0}
Expiring Certificates: ${stats?.compliance?.expiringSoon || 0}
Expired Certificates: ${stats?.compliance?.expired || 0}
------------------------------
Generated by KIAL AVSEC Mobile App
      `;
      await Share.share({
        message: summary,
        title: 'Security Compliance Report',
      });
    } catch (error) {
      Alert.alert('Error', 'Could not share report.');
    }
  };

  if (loading) return <LoadingSpinner message="Loading dashboard..." />;

  // Sample data fallback for demonstration as requested
  const s = stats || {
    totalEntities: 1,
    totalStaff: 1,
    pendingApprovals: 0,
    totalCertificates: 2,
    complianceRate: 0,
    compliance: { expiringSoon: 0, expired: 2 }
  };

  // If data exists but is zero, prioritize the visual of the reference image
  const expiringCount = s.compliance?.expiringSoon ?? 0;
  const expiredCount = s.compliance?.expired ?? 2;

  return (
    <SafeAreaView style={styles.safe} edges={['top']}>
      <StatusBar barStyle="light-content" backgroundColor={colors.primary} />

      {/* Header */}
      <View style={styles.header}>
        <View style={styles.headerLeft}>
          <Image source={require('../../assets/logo.png')} style={styles.headerLogo} resizeMode="contain" />
          <View>
            <Text style={styles.greeting}>Good day,</Text>
            <Text style={styles.userName}>{user?.name || 'CSO Officer'}</Text>
          </View>
        </View>
        <TouchableOpacity onPress={logout} style={styles.logoutBtn}>
          <Ionicons name="log-out-outline" size={22} color={colors.white} />
        </TouchableOpacity>
      </View>

      <ScrollView
        style={styles.scroll}
        contentContainerStyle={styles.content}
        refreshControl={<RefreshControl refreshing={refreshing} onRefresh={onRefresh} tintColor={colors.primary} />}
        showsVerticalScrollIndicator={false}
      >
        <View style={styles.dashboardTitleRow}>
          <Text style={styles.dashboardTitle}>Dashboard</Text>
          <TouchableOpacity style={styles.shareBtn} onPress={handleShare}>
            <Ionicons name="share-social-outline" size={16} color={colors.primary} />
            <Text style={styles.shareBtnText}>Share Report</Text>
          </TouchableOpacity>
        </View>
        <Text style={styles.dashboardSub}>Overview of security compliance</Text>

        {/* Expiring Alert Card - Full Width at Top */}
        <TouchableOpacity 
          style={styles.alertCardFull}
          onPress={() => navigation.navigate('SystemOverview')}
        >
          <View style={styles.alertHeaderRow}>
            <View style={styles.alertIconWrap}>
              <Ionicons name="warning-outline" size={20} color={colors.danger} />
            </View>
            <View>
              <Text style={styles.alertLabel}>CERTIFICATES EXPIRING SOON</Text>
              <Text style={styles.alertValue}>{expiringCount}</Text>
            </View>
          </View>
          
          <View style={styles.criticalBadge}>
            <View style={styles.criticalDot} />
            <Text style={styles.criticalLabel}>CRITICAL ACTION</Text>
          </View>
          <Text style={styles.criticalDesc}>
            {expiredCount} certificates have already expired. Immediate renewal required.
          </Text>
        </TouchableOpacity>

        {/* 2-Column Grid for Primary Stats */}
        <View style={styles.statsRow}>
          <StatsCard label="Active Entities" value={s.totalEntities ?? 1} icon="business-outline" color={colors.primary} />
          <StatsCard label="Total Staff" value={s.totalStaff ?? 1} icon="person-outline" color="#6366F1" />
        </View>
        <View style={styles.statsRow}>
           <StatsCard label="Pending Approvals" value={s.pendingApprovals ?? 0} icon="checkmark-done-outline" color={colors.success} />
           <View style={{ flex: 1, marginHorizontal: 5 }} /> 
        </View>

        <View style={styles.sectionDivider} />

        {/* Summary Grids */}
        <View style={styles.statsRow}>
          {/* Certificates Card */}
          <View style={styles.statsBaseCard}>
             <Text style={styles.cardHeaderTitle}>Certificates</Text>
             <Text style={styles.cardHeaderValue}>{s.totalCertificates ?? 2}</Text>
             <Text style={styles.cardHeaderSub}>Total issued</Text>
             <View style={styles.donutPlaceholder}>
                <View style={[styles.donutInner, { borderColor: colors.primary, borderTopColor: 'transparent' }]} />
             </View>
          </View>

          {/* Compliance Rate Card */}
          <View style={styles.statsBaseCard}>
             <Text style={styles.cardHeaderTitle}>Compliance Rate</Text>
             <Text style={styles.cardHeaderValue}>{s.complianceRate ?? 0}%</Text>
             <Text style={styles.cardHeaderSub}>Valid ratio</Text>
             <View style={styles.donutPlaceholder}>
                <View style={[styles.donutInner, { borderColor: colors.border }]} />
             </View>
          </View>
        </View>

        <View style={styles.statsRow}>
          {/* Entities Status Card */}
          <View style={styles.statsBaseCard}>
             <View style={styles.cardCircleIcon}>
                <Ionicons name="checkmark-done" size={16} color={colors.primary} />
             </View>
             <Text style={styles.entityStatusText}>All entity documents are valid.</Text>
             <TouchableOpacity onPress={() => navigation.navigate('Entities')}>
                <Text style={styles.viewAllLink}>View All Entities →</Text>
             </TouchableOpacity>
          </View>
          <View style={{ flex: 1, marginHorizontal: 5 }} />
        </View>

        <View style={styles.sectionDivider} />

        {/* Critical Certificates Large Card */}
        <View style={styles.largeCriticalCard}>
          <View style={styles.criticalCardHeader}>
            <View style={styles.criticalShieldWrap}>
              <Ionicons name="shield-checkmark-outline" size={20} color={colors.danger} />
            </View>
            <View>
              <Text style={styles.criticalCardTitle}>Critical Certificates</Text>
              <Text style={styles.criticalCardSub}>Expiring soon or already expired</Text>
            </View>
          </View>

          <View style={styles.allClearContent}>
            <View style={styles.largeCheckCircle}>
               <Ionicons name="checkmark-outline" size={32} color={colors.success} />
            </View>
            <Text style={styles.allClearTitle}>All Clear</Text>
            <Text style={styles.allClearSub}>
              There are no operational staff certificates that are expired or expiring soon.
            </Text>
          </View>
        </View>

        <View style={styles.sectionDivider} />

        {/* Quick Actions */}
        <Text style={styles.sectionTitle}>Quick Actions</Text>
        <View style={styles.actionsGrid}>
          {[
            { label: 'Add Staff', icon: 'person-add-outline', screen: 'Staff', color: colors.primary },
            { label: 'View Approvals', icon: 'checkmark-circle-outline', screen: 'Approvals', color: colors.warning },
            { label: 'Entities', icon: 'business-outline', screen: 'Entities', color: '#6366F1' },
            { label: 'System Overview', icon: 'analytics-outline', screen: 'SystemOverview', color: colors.info },
          ].map((action) => (
            <TouchableOpacity
              key={action.label}
              style={styles.actionCard}
              onPress={() => navigation.navigate(action.screen)}
              activeOpacity={0.8}
            >
              <View style={[styles.actionIcon, { backgroundColor: action.color + '18' }]}>
                <Ionicons name={action.icon} size={24} color={action.color} />
              </View>
              <Text style={styles.actionLabel}>{action.label}</Text>
            </TouchableOpacity>
          ))}
        </View>

        {/* Recent Activity */}
        {s.recentActivity?.length > 0 && (
          <>
            <Text style={styles.sectionTitle}>Recent Activity</Text>
            {s.recentActivity.slice(0, 5).map((item, i) => (
              <View key={i} style={styles.activityRow}>
                <View style={styles.activityDot} />
                <View style={{ flex: 1 }}>
                  <Text style={styles.activityText}>{item.description || item.action}</Text>
                  <Text style={styles.activityTime}>{new Date(item.createdAt).toLocaleString()}</Text>
                </View>
              </View>
            ))}
          </>
        )}
      </ScrollView>
    </SafeAreaView>
  );
}

const styles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: colors.primary },
  header: {
    flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between',
    paddingHorizontal: 20, paddingVertical: 12,
    backgroundColor: colors.primary,
  },
  headerLeft: { flexDirection: 'row', alignItems: 'center', gap: 10 },
  headerLogo: { width: 36, height: 36 },
  greeting: { fontSize: typography.sm, fontFamily: typography.fontRegular, color: 'rgba(255,255,255,0.7)' },
  userName: { fontSize: typography.lg, fontFamily: typography.fontBold, color: colors.white },
  logoutBtn: { padding: 8, borderRadius: 10, backgroundColor: 'rgba(255,255,255,0.15)' },
  scroll: { flex: 1, backgroundColor: colors.background, borderTopLeftRadius: 24, borderTopRightRadius: 24 },
  content: { padding: 20, paddingBottom: 40 },
  dashboardTitleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 10, marginBottom: 4 },
  dashboardTitle: { fontSize: typography.xl, fontFamily: typography.fontBold, color: colors.text },
  shareBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, backgroundColor: colors.white, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8, borderWidth: 1, borderColor: colors.border },
  shareBtnText: { fontSize: 12, fontFamily: typography.fontSemiBold, color: colors.textSecondary },
  dashboardSub: { fontSize: typography.xs, fontFamily: typography.fontRegular, color: colors.textMuted, marginBottom: 20 },
  
  topStatsRow: { flexDirection: 'row', gap: 12, marginBottom: 12 },
  leftStatsCol: { flex: 1.5, gap: 12 },
  statsRow: { flexDirection: 'row', gap: 12, marginBottom: 12, paddingHorizontal: 5 },

  alertCardFull: { 
     backgroundColor: colors.surface, 
     borderRadius: 16, 
     padding: 20, 
     marginBottom: 20,
     elevation: 4, 
     shadowColor: '#000', 
     shadowOpacity: 0.1, 
     shadowRadius: 12, 
     shadowOffset: { width: 0, height: 6 },
     borderWidth: 1,
     borderColor: colors.dangerLight,
  },
  alertHeaderRow: { flexDirection: 'row', alignItems: 'center', gap: 15, marginBottom: 15 },
  alertIconWrap: { width: 44, height: 44, borderRadius: 12, backgroundColor: colors.dangerLight, alignItems: 'center', justifyContent: 'center' },
  alertValue: { fontSize: 36, fontFamily: typography.fontBold, color: colors.text, lineHeight: 40 },
  alertLabel: { fontSize: 10, fontFamily: typography.fontBold, color: colors.textMuted, letterSpacing: 0.8 },
  
  criticalBadge: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 10, marginBottom: 8 },
  criticalDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.danger },
  criticalLabel: { fontSize: 11, fontFamily: typography.fontBold, color: colors.danger, letterSpacing: 0.5 },
  criticalDesc: { fontSize: 12, fontFamily: typography.fontRegular, color: colors.textSecondary, lineHeight: 18 },

  sectionDivider: { height: 1, backgroundColor: colors.border, marginVertical: 10, marginHorizontal: 10 },

  statsBaseCard: { flex: 1, backgroundColor: colors.surface, borderRadius: 16, padding: 16, elevation: 2, shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 8, shadowOffset: { width: 0, height: 3 }, marginHorizontal: 5 },
  cardHeaderTitle: { fontSize: 13, fontFamily: typography.fontBold, color: colors.text, marginBottom: 2 },
  cardHeaderValue: { fontSize: 24, fontFamily: typography.fontBold, color: colors.text },
  cardHeaderSub: { fontSize: 10, fontFamily: typography.fontRegular, color: colors.textMuted, marginBottom: 15 },
  donutPlaceholder: { height: 70, alignItems: 'center', justifyContent: 'center' },
  donutInner: { width: 70, height: 70, borderRadius: 35, borderWidth: 8, borderColor: colors.border },

  cardCircleIcon: { width: 32, height: 32, borderRadius: 16, backgroundColor: colors.primary + '18', alignItems: 'center', justifyContent: 'center', marginBottom: 12 },
  entityStatusText: { fontSize: 13, fontFamily: typography.fontMedium, color: colors.text, marginBottom: 8 },
  viewAllLink: { fontSize: 12, fontFamily: typography.fontBold, color: colors.primary },

  largeCriticalCard: { backgroundColor: colors.surface, borderRadius: 20, padding: 20, marginBottom: 20, elevation: 2, shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 10, shadowOffset: { width: 0, height: 4 }, borderWidth: 1, borderColor: colors.border },
  criticalCardHeader: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 30 },
  criticalShieldWrap: { width: 36, height: 36, borderRadius: 10, backgroundColor: colors.dangerLight, alignItems: 'center', justifyContent: 'center' },
  criticalCardTitle: { fontSize: 16, fontFamily: typography.fontBold, color: colors.text },
  criticalCardSub: { fontSize: 11, fontFamily: typography.fontRegular, color: colors.textMuted },
  
  allClearContent: { alignItems: 'center', paddingVertical: 20 },
  largeCheckCircle: { width: 64, height: 64, borderRadius: 32, backgroundColor: colors.success + '18', alignItems: 'center', justifyContent: 'center', marginBottom: 16 },
  allClearTitle: { fontSize: typography.lg, fontFamily: typography.fontBold, color: colors.text, marginBottom: 8 },
  allClearSub: { fontSize: 12, fontFamily: typography.fontRegular, color: colors.textMuted, textAlign: 'center', paddingHorizontal: 20, lineHeight: 18 },

  activityText: { fontSize: typography.sm, fontFamily: typography.fontRegular, color: colors.text },
  activityTime: { fontSize: typography.xs, fontFamily: typography.fontRegular, color: colors.textMuted, marginTop: 2 },
  
  sectionTitle: { fontSize: typography.base, fontFamily: typography.fontSemiBold, color: colors.text, marginBottom: 12, marginTop: 8 },
  actionsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, marginBottom: 24 },
  actionCard: { width: '47%', backgroundColor: colors.surface, borderRadius: 14, padding: 16, alignItems: 'center', gap: 10, elevation: 2, shadowColor: '#000', shadowOpacity: 0.05, shadowRadius: 8, shadowOffset: { width: 0, height: 3 } },
  actionIcon: { width: 48, height: 48, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  actionLabel: { fontSize: typography.sm, fontFamily: typography.fontMedium, color: colors.text, textAlign: 'center' },

  activityRow: { flexDirection: 'row', alignItems: 'flex-start', gap: 12, marginBottom: 14, backgroundColor: colors.surface, borderRadius: 12, padding: 14, elevation: 1 },
  activityDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: colors.primary, marginTop: 5 },
});
